import Head from "next/head";
import Image from "next/image";

import styles from "../styles/Home.module.css";
import banner from "../public/banner_image.png";
import brand from "../public/brand.png";
import icon1 from "../public/icon1.png";
import icon2 from "../public/icon2.png";
import icon3 from "../public/icon3.png";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cloudfire Esport</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="min-h-screen bg-[#000D2F] w-full text-white">
        {/* NAVBAR */}
        <div className="container mx-auto">
          <nav className="w-full h-[160px] bg-transparent flex items-center justify-between">
            <div className="navbar-brand">
              <Image src={brand} alt="Cloudfire Esport" />
            </div>
            <div className="nav-link">
              <ul className="flex space-x-11 items-center transition-all">
                <li className="hover:border-b-2 hover:border-[#FDC500]">
                  <a href="">Home</a>
                </li>
                <li className="hover:border-b-2 hover:border-[#FDC500]">
                  <a href="">Games</a>
                </li>
                <li className="hover:border-b-2 hover:border-[#FDC500]">
                  <a href="">Teams</a>
                </li>
                <li className="hover:border-b-2 hover:border-[#FDC500]">
                  <a href="">Tournaments</a>
                </li>
                <li className="hover:border-b-2 hover:border-[#FDC500]">
                  <a href="">Store</a>
                </li>
                <li>
                  <a
                    href=""
                    className="text-[#000D2F] bg-[#FDC500] hover:bg-[#e7b604] w-[120px] h-[50px] p-[11px] rounded-full flex items-center justify-center"
                  >
                    Sign In
                  </a>
                </li>
              </ul>
            </div>
          </nav>
        </div>

        {/* HERO SECTION */}
        <div className="mt-[70px] w-full">
          <div className="container mx-auto items-center flex justify-between">
            <div className="left">
              <p className="text-lg text-[#7E8CAC] font-normal leading-7">
                Halo Gamers,
              </p>
              <h1 className="font-bold text-5xl leading-[63px] text-white mb-8">
                Ikuti Turnamen & Dapatkan <br /> Pengalaman Baru
              </h1>
              <p className="font-normal text-lg leading-8 text-white">
                Kami menyediakan jutaan cara untuk membantu <br /> players
                menjadi pemenang sejati.
              </p>
              <div className="cta mt-[50px] flex items-center space-x-[20px]">
                <button className="w-[200px] h-[50px] rounded-full bg-[#E2A917] flex items-center justify-center font-medium text-lg text-[#000D2F] leading-7">
                  Cari Turnamen
                </button>
                <a
                  href=""
                  className="text-lg font-normal leading-7 underline underline-offset-4"
                >
                  Learn More
                </a>
              </div>
            </div>
            <div className="right">
              <Image src={banner} alt="hero" className="aspect-square" />
            </div>
          </div>
        </div>

        {/* HOW IT WORKS */}
        <div className="mt-[120px] w-full">
          <div className="container mx-auto items-center flex flex-col">
            <h1 className="font-bold text-3xl leading-10 text-center mb-16">
              It’s Really That <br /> Easy to Win the Game
            </h1>
            <div className="flex items-center justify-between w-full px-[50px]">
              <div className="card bg-[#0C1F63] rounded-3xl w-[400px] h-[300px] p-7">
                <Image src={icon1} alt="icon1" className="aspect-square" />
                <p className="mt-8 text-2xl font-semibold leading-8">
                  1. Start
                </p>
                <p className="mt-2 font-normal text-lg leading-8">
                  Pilih salah satu turnamen <br /> yang ingin kamu ikuti.
                </p>
              </div>
              <div className="card bg-[#0C1F63] rounded-3xl w-[400px] h-[300px] p-7">
                <Image src={icon2} alt="icon1" className="aspect-square" />
                <p className="mt-8 text-2xl font-semibold leading-8">
                  2. Fill Up
                </p>
                <p className="mt-2 font-normal text-lg leading-8">
                  Masukkan daftar anggota tim <br /> kamu.
                </p>
              </div>
              <div className="card bg-[#0C1F63] rounded-3xl w-[400px] h-[300px] p-7">
                <Image src={icon3} alt="icon1" className="aspect-square" />
                <p className="mt-8 text-2xl font-semibold leading-8">
                  3. Be a Winner
                </p>
                <p className="mt-2 font-normal text-lg leading-8">
                  Lakukan latihan bareng tim <br /> dan jadilah juara.
                </p>
              </div>
            </div>
          </div>
        </div>

        <div className="mt-[1000px] w-full">a</div>
      </main>
    </div>
  );
}
